name: Auto Ping Analyzer Update

on:
  schedule:
    - cron: "0 */3 * * *"     # اجرای خودکار هر 3 ساعت
  workflow_dispatch:          # اجرای دستی

jobs:
  run-ping-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          pip install requests

      - name: Clear Output Files Content (Not delete files)
        run: |
          echo "Clearing content of ping.txt and best.txt..."
          > ping.txt  # پاک کردن محتویات فایل
          > best.txt  # پاک کردن محتویات فایل

      - name: Run cl99.py
        run: |
          echo "Running Analyzer..."
          python3 cl99.py

      - name: Commit & Push Results
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions Bot"
          git add ping.txt best.txt
          git commit -m "Auto update results"
          git push
        continue-on-error: true
