name: Sub Checker CL60

on:
  workflow_dispatch:
  schedule:
    - cron: " */30 * * * *"   # اجرای cl20.py هر ۱ ساعت

permissions:
  contents: write

jobs:
  cl60-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install requests psutil retrying PyYaml || echo "skip install"
      - run: |
          rm -f final60.txt normal60.txt
          timeout 300s python cl60.py || echo "❌ cl60.py failed or skipped"
      - run: |
          if [[ -s final60.txt || -s normal60.txt ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add final60.txt normal60.txt
            git commit -m "auto update from cl60.py [skip ci]" || echo "No changes"
            git push || echo "skip push"
          else
            echo "⚠️ final60.txt یا normal60.txt خالی یا موجود نیست، commit نشد"
          fi
